# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: auditd
  namespace: garden-local
immutable: true
data:
  auditd: |
    apiVersion: rsyslog-relp.extensions.gardener.cloud/v1alpha1
    kind: Auditd
    auditRules: |
      ## First rule - delete all
      -D
      ## Increase the buffers to survive stress events.
      ## Make this bigger for busy systems
      -b 8192
      ## This determine how long to wait in burst of events
      --backlog_wait_time 60000
      ## Set failure mode to syslog
      -f 1
      ## Ignore errors when loading rules
      -i
      -a exit,always -F arch=b64 -S execve -S execveat -F euid=0 -F auid>0 -F auid!=-1 -F key=privilege_escalation
      -a exit,always -F arch=b64 -S setuid -S setreuid -S setgid -S setregid -F auid>0 -F auid!=-1 -F key=privilege_escalation
      -a exit,always -F dir=/etc -F perm=wa -F key=system_integrity
