# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0


images:
  rsyslog: image-repository:image-tag
  pullPolicy: IfNotPresent

replicaCount: 1