application:
  webhookConfig:
    caBundle: |
      -----BEGIN CERTIFICATE-----
      MIIDSjCCAjKgAwIBAgIUaX+WnEWcMdjr2Xy13PejUIBl85IwDQYJKoZIhvcNAQEL
      BQAwPTE7MDkGA1UEAxMyY2EtZ2FyZGVuZXItZXh0ZW5zaW9uLXNob290LXJzeXNs
      b2ctcmVscC1hZG1pc3Npb24wHhcNMjMwNzAxMTMxMDAwWhcNMjgwNjI5MTMxMDAw
      WjA9MTswOQYDVQQDEzJjYS1nYXJkZW5lci1leHRlbnNpb24tc2hvb3QtcnN5c2xv
      Zy1yZWxwLWFkbWlzc2lvbjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
      AMMk+5Y9asgFwroHvT07bRx7OeUnyhPz8zhDKr6oe+0QfYq75FODU5BL7ZrQJigZ
      lqny4brPLkhmLyDABb7TE9jLvOmb+3S/fd1Z+n6C0gvGMtLDSMypZz7F4YF6bLQl
      ofa1Qsf1vXwm+3XTUJ49RN2WC6Douyzh7tXZbpzEyc8n/yKZdCYNdN0zj1IkQPej
      A7B/bPRLN5UUSYtQ9VC3RtnnixFYM6NZJnsELTIDmfhj91DKXLHW3Y9gKCcEAAH0
      VgPLNdrUi1DAtu4tjfvfoKCDqf1/tTQO0sUW/uDSj8YyenOqJNKVBWFAxevsxiI4
      03kOe+LzaxvhoTxchlwFNXUCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1Ud
      EwEB/wQFMAMBAf8wHQYDVR0OBBYEFGH0WVVEEPQTyHoh7AMRYi3hPkZ/MA0GCSqG
      SIb3DQEBCwUAA4IBAQCRmwqflFeYKZLqquYOPIyUZLWlKjwPLnNh+ZolIrZ3mrzW
      lWtKx76OnONk7SO89oDJOYHuJufJlT9RCleyJTduKtwT6JG6o/uxJtNlT2pJf/CD
      ND5MlBxq0XF/ZaLec46YDtUXH7seqEPzMPAt/O/RwxkYqPgJtBggxfTHCpbcdCIx
      xasLp4MlpERtSHbrDu4gCzDs6NyKAEJzkpmTc3Tm0o2SFA+zEY0HdPnDep/iEORA
      bouKVDcFQMoluZrCWWZZDRktjrd8zvRuF/gsTRBQNwrc4lUQ6Q0LgnKBcTPtKnwN
      8RXuztXkOHPc8Tk1qquviRrpKAkuTRScAdBzpiAT
      -----END CERTIFICATE-----

runtime:
  webhookConfig:
    tls:
      crt: |
        -----BEGIN CERTIFICATE-----
        MIIE2zCCA8OgAwIBAgIUAXm+NewSbkqkE3nLG3M5OCMcjGwwDQYJKoZIhvcNAQEL
        BQAwPTE7MDkGA1UEAxMyY2EtZ2FyZGVuZXItZXh0ZW5zaW9uLXNob290LXJzeXNs
        b2ctcmVscC1hZG1pc3Npb24wHhcNMjMwNzAxMTMxMDAwWhcNMzMwNjI4MTMxMDAw
        WjBTMVEwTwYDVQQDE0hnYXJkZW5lci1leHRlbnNpb24tc2hvb3QtcnN5c2xvZy1y
        ZWxwLWFkbWlzc2lvbi5nYXJkZW4uc3ZjLmNsdXN0ZXIubG9jYWwwggEiMA0GCSqG
        SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDQaJr8mldbt/6XKtMfNNkcFYijCeHP2hWf
        QKWzfaks1cayHWPDPsEwqFltc3D9v/3pv6VMy4u234jzVG6flx26l5W+d77Ro915
        CeoH4bjad3e//KVhgfzSorEx67Sl07irMEzJJwmoFYudluZ1Cq3cZbqPQ2PY7F9e
        jxxCvaB1zx/85xLKR+1YCrQEob70Jnwcmtiyf06OUze+Qt0i0L7pK94bShr7BFMY
        AzeFJEkLpnjHuM5GSOLl3ZCne0T8o46qPGKtFd9sytR/u6t7+DueOvO5x+HcBwk6
        nf3ejkzmS9cEj43f2sae3IQYXTSokBjwoJ2s84QXW17b5VR0HvujAgMBAAGjggG7
        MIIBtzAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0T
        AQH/BAIwADAdBgNVHQ4EFgQUKcxauf4F7MCCngaCv4+v87gxJgQwHwYDVR0jBBgw
        FoAUYfRZVUQQ9BPIeiHsAxFiLeE+Rn8wggFABgNVHREEggE3MIIBM4IvZ2FyZGVu
        ZXItZXh0ZW5zaW9uLXNob290LXJzeXNsb2ctcmVscC1hZG1pc3Npb26CNmdhcmRl
        bmVyLWV4dGVuc2lvbi1zaG9vdC1yc3lzbG9nLXJlbHAtYWRtaXNzaW9uLmdhcmRl
        boI6Z2FyZGVuZXItZXh0ZW5zaW9uLXNob290LXJzeXNsb2ctcmVscC1hZG1pc3Np
        b24uZ2FyZGVuLnN2Y4JCZ2FyZGVuZXItZXh0ZW5zaW9uLXNob290LXJzeXNsb2ct
        cmVscC1hZG1pc3Npb24uZ2FyZGVuLnN2Yy5jbHVzdGVygkhnYXJkZW5lci1leHRl
        bnNpb24tc2hvb3QtcnN5c2xvZy1yZWxwLWFkbWlzc2lvbi5nYXJkZW4uc3ZjLmNs
        dXN0ZXIubG9jYWwwDQYJKoZIhvcNAQELBQADggEBAGXKmk7mpER5ZavjqY+U6pnX
        qYguY2Xd6Vt/u48OBAKWuLAf1fX2+rMZynqad2omj6PUmCEhGeHZs6sQmqLI7JL6
        nbaxahmVBoiRr4EZM/1mit2TSiklO7eLR2ThoQzkEyb8VSf6PVvFziSL7rr/IVtM
        nyxPGpAD22S061eBNIDbMxEwowjDkq+MhR4Rpq/O+OExDjBj9O0b9NPfpHH6umI7
        O9+6H7xCgds7ocPDXEqzJh1cLmav3vuJm/nINr82dcy72R/5+gQWJh+pwbyMVJ4K
        MnTfLj7RbOI5vGi+wkYhcWn6l/wPQ/E/XlQHMw3M0iSyDMhp0muXKBRr9VMvIJI=
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEA0Gia/JpXW7f+lyrTHzTZHBWIownhz9oVn0Cls32pLNXGsh1j
        wz7BMKhZbXNw/b/96b+lTMuLtt+I81Run5cdupeVvne+0aPdeQnqB+G42nd3v/yl
        YYH80qKxMeu0pdO4qzBMyScJqBWLnZbmdQqt3GW6j0Nj2OxfXo8cQr2gdc8f/OcS
        ykftWAq0BKG+9CZ8HJrYsn9OjlM3vkLdItC+6SveG0oa+wRTGAM3hSRJC6Z4x7jO
        Rkji5d2Qp3tE/KOOqjxirRXfbMrUf7ure/g7njrzucfh3AcJOp393o5M5kvXBI+N
        39rGntyEGF00qJAY8KCdrPOEF1te2+VUdB77owIDAQABAoIBAHGK3A2NJNTybED9
        cuJIj5ROYw+4XY85GJiXxu8AIkAsA8GcY3LG6MfSoE4SG9gTVomYAL3TEz5BkMJJ
        GK/Xy7mRxmJrqMlcRlggP6Glp2lWtyYgxhVWlWBIhNNWwCesLqsNeHgKzacGffcQ
        dGQFum0d+0L8CxTuypKg01vFJfuoLPu8ckSdrd+Col9KUCKV60tOZw8Do+tSJgYU
        n7+iL6lXvYQ3ESPHTAXlJPE1TJwvzaGrIDWhvUIxBvnkad0fBbTQRQq90Q3Ae/fu
        fXE3kEAP/ke60/WZ0xuPhvHSVPcizvnIHOPe7S1wTEEh+4tRvg5FdFuCCginZmvP
        /koGs3kCgYEA+9pOyDLmmFYskibOZYZOL7dIMRpnVxQ53tZnwB3uyvbi65QXzX7d
        v5fVJzJcvtHZgy7gbBzGSoSCZsEPd99wdBWojIp9SKga4rF/897HgJNtt4GLfkMr
        5PmLZY4gR4+JCxYd2Z0KIitg/pa9yxCcJPA8a1IzNr3vuAajHDDnhVUCgYEA09co
        XNLnoJVeo3vdsUDjtN+Zk4tP2V73vzB3uABCL0mgF0Yj39Zb2YUtFv74HCLeUaPw
        UxJCNeyZmP9plmWhYn7LrSjHCWrjVxOy5Fz9yQ/cpAxn3ozOFl7dtNkFV6VFxl7c
        HUy0HPd7xHnmKOtScwImyhrdZpbkTj2c8k5Z/RcCgYBMOls2BRH+cbaz1cMKv4fS
        sWrMUe2NUbXiWIq2f1jTXb55By3dKNT9NHtzja68os9vATU0A9GQpGLDrxN7eMmU
        mSmWwCQDZb4ddxP/QCKqK/U9YZxS7wnOGCm05zul7S/RhzQptXpntTF6XS281J4u
        H/hpk0uk+gAgdwHPeo3YsQKBgQCkbYvpyNZ7IZWsxbdFHz3fpfM5v9eBvKIGZ6N1
        UdYNiFNX3Vx5IJR4mVNvVwbUKAhyTBJ9GF4GJxjt1cpqL4Z9wjdrt4wOdkXxz9t6
        P+fJCaPUPcDd0GMioA3sksr/xcwL9pNZtrDTDxGlZozM1CNSG6hqFUImoBaj2FUb
        Cs/0jwKBgQCLwxgrn2o62s8hriEcHNnOzVTfFvSmhKBaivpuMVYieBtujw0L69M7
        8oK12ythn26/8ngl3jUQ69jDg8T0ejjCYfsjn/XcuhEXbXAK8cmQ4keNOMXt4Nz7
        S4vSAVdZ8nR7MSUkM+RigxUv8KtN3+Wqtnlv4qZfkB4JNeP2h2NkkA==
        -----END RSA PRIVATE KEY-----
